server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: false

      routes:

        - id: payment-service
          uri: http://payment-service:8081
          predicates:
            - Path=/api/v1/payments/**

        - id: fraud-detection-service
          uri: http://fraud-detection-service:8082
          predicates:
            - Path=/api/v1/fraud/**
          filters:
            - name: CircuitBreaker
              args:
                name: fraudDetectionCircuitBreaker
                fallbackUri: forward:/fallback/fraud

        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/api/v1/notifications/**

        - id: ai-reasoning-service
          uri: http://ai-reasoning-service:8084
          predicates:
            - Path=/api/v1/ai/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

  endpoint:
    gateway:
      enabled: true
